rails: "https://www.railstutorial.org/"
michael: "http://www.michalhartl.com"
newsrail: "http://news.railstutorial.org"
help: https://www.railstutorial.org/help
book: https://www.railstutorial.org/book
